name: Release from tag

on:
  push:
    tags:
      - '*'  # Auslösen bei jedem neuen Tag

jobs:
  release-automatisch:
    permissions:
      contents: write  # Ermöglicht das Schreiben eines Releases

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create GitHub Release from tag
        uses: ghalactic/github-release-from-tag@v5
        with:
          generateReleaseNotes: true
